F#7 rectangular tables
ucuapps/robert pull request #14
Opened 2018-03-09 12:36 UTC by deathtanks

2018-03-10 22:55 UTC, AndriyPt requested changes

2018-03-10 22:55 UTC, AndriyPt commented on robert_gazebo/models/table_rectangular_low/model.sdf
> +            <uri>model://robert_gazebo/meshes/table_rectangular_low_collisium.dae</uri>
wrong DAE file name :)

2018-03-10 22:59 UTC, AndriyPt commented
Please fix small issue of file name and happy to merge :)

2018-03-12 11:54 UTC, sophia-tslk commented
Problem solved, everything is ok.

2018-03-13 21:17 UTC, AndriyPt commented
@sophia-tslk @deathtanks  Please add `.DS_Store` to .gitignore and delete these files from this branch :)

2018-03-13 21:21 UTC, AndriyPt commented
please remove files 
```
robert/robert_gazebo/models/puffy/puffy.config
robert/robert_gazebo/models/puffy/puffy.sdf
```
from this branch :)
Please also restore file `robert/robert_gazebo/worlds/ucu.world`

2018-03-16 12:14 UTC, sophia-tslk commented
done.

2018-03-16 13:12 UTC, v-lavrushko commented
Done.

2018-03-17 15:12 UTC, AndriyPt approved these changes

2018-03-17 15:13 UTC, merged