F#12 fire rescue box
ucuapps/robert pull request #21
Opened 2018-03-16 13:13 UTC by v-lavrushko

Fire rescue box done

2018-03-17 16:23 UTC, AndriyPt requested changes

2018-03-17 16:23 UTC, AndriyPt commented on robert_gazebo/models/fire_rescue/model.sdf
> +        </link>
please add inertia properties

2018-03-17 16:23 UTC, AndriyPt commented on robert_gazebo/worlds/ucu.world
> +    <include>
please remove debug model

2018-04-01 20:45 UTC, AndriyPt commented
Incorrect scale and collision model
![image](https://user-images.githubusercontent.com/10820297/38177236-c6bc7ffe-3606-11e8-8885-c4394973a1ac.png)

2018-04-12 18:13 UTC, AndriyPt requested changes
Single comment and will merge

2018-04-12 18:13 UTC, AndriyPt commented on robert_gazebo/models/fire_rescue/model.sdf
> +        <static>true</static>
in order to have interaction with the object in simulation please set this property to false

2018-04-14 18:22 UTC, LAnastasiia commented on robert_gazebo/models/fire_rescue/model.sdf
> +        <static>true</static>
Done

2018-04-16 06:29 UTC, AndriyPt approved these changes

2018-04-16 06:30 UTC, merged