F#20 pictures
ucuapps/robert pull request #22
Opened 2018-03-17 19:47 UTC by sophia-tslk

2018-03-18 08:55 UTC, AndriyPt requested changes
I would advise to use Leobot approach e.g. https://github.com/ros-ukraine/leobot/tree/kinetic-devel/leobot_gazebo/models/room1_img3 which do not require dae files only JPG :)

2018-03-18 08:55 UTC, AndriyPt commented on .gitignore
> +robert_gazebo/meshes/.DS_Store
these is no need to add .DS_Store ignore in each folder. Rule in row no 86 will ignore it in every folder.

2018-03-22 10:35 UTC, sophia-tslk commented
Done.

2018-03-24 19:45 UTC, AndriyPt requested changes
Please remove debug code from ucu.world and optionally add inertia to pictures.

2018-03-24 21:12 UTC, sophia-tslk commented
Done

2018-03-25 13:55 UTC, sophia-tslk commented
Done

2018-03-25 19:22 UTC, AndriyPt approved these changes

2018-03-25 19:22 UTC, merged