F#8 chair models
ucuapps/robert pull request #24
Opened 2018-03-19 07:03 UTC by LAnastasiia

2018-03-19 23:00 UTC, AndriyPt requested changes
Please remove blend1 files

2018-03-19 23:00 UTC, AndriyPt commented on robert_gazebo/worlds/ucu.world
> +    <include>
Please remove debug code

2018-03-20 10:33 UTC, LAnastasiia commented on robert_gazebo/worlds/ucu.world
> +    <include>
Done

2018-03-22 17:19 UTC, AndriyPt commented
Bad scale of the objects
![image](https://user-images.githubusercontent.com/10820297/37786669-e6c77212-2e05-11e8-8163-3a75e0a37860.png)

2018-03-28 10:29 UTC, LAnastasiia commented
Done

2018-04-01 20:58 UTC, AndriyPt approved these changes

2018-04-01 20:58 UTC, merged