F#10 trapezoid table models
ucuapps/robert pull request #27
Opened 2018-03-19 20:48 UTC by LAnastasiia

closes #10

2018-03-19 23:02 UTC, AndriyPt requested changes
Please remove blend1 files and not used STL files

2018-03-19 23:02 UTC, AndriyPt commented on robert_gazebo/worlds/ucu.world
> +    <include>
please remove debug code

2018-03-20 13:27 UTC, LAnastasiia commented on robert_gazebo/worlds/ucu.world
> +    <include>
Done

2018-03-22 17:38 UTC, AndriyPt commented
Bad scale of the table
![image](https://user-images.githubusercontent.com/10820297/37787790-7a9cd1ba-2e08-11e8-9aa9-1dc1f2dbdaca.png)

2018-03-30 13:34 UTC, LAnastasiia commented
Done.

2018-04-01 21:05 UTC, AndriyPt requested changes
Please remove files with extension blend1 and stil

2018-04-02 10:03 UTC, LAnastasiia commented
Done.

2018-04-12 18:46 UTC, AndriyPt approved these changes

2018-04-12 18:47 UTC, merged