F#25 lectorium chair
ucuapps/robert pull request #34
Opened 2018-03-22 11:01 UTC by LAnastasiia

closes #25

2018-03-22 17:26 UTC, AndriyPt requested changes
please remove redundant mesges

2018-03-22 17:26 UTC, AndriyPt commented on robert_gazebo/models/lectorium_chair_orange/model.sdf
> +  <model name="locker_008">
wrong model name :)

2018-03-22 17:26 UTC, AndriyPt commented on robert_gazebo/worlds/office.world
> +office.world<?xml version="1.0" ?>
please remove redundant text

2018-03-29 13:17 UTC, LAnastasiia commented
Done

2018-03-31 09:52 UTC, LAnastasiia commented
Done.

2018-04-01 21:06 UTC, AndriyPt requested changes
Please revert all your changes in office.world file

2018-04-02 14:38 UTC, LAnastasiia commented
Done.

2018-04-12 19:01 UTC, AndriyPt approved these changes

2018-04-12 19:01 UTC, merged