qr code generator
ucuapps/robert pull request #41
Opened 2018-03-30 08:04 UTC by v-lavrushko

closes #30 
Please check my qr code generator program

2018-04-01 21:42 UTC, AndriyPt commented
I am getting this error
```bash
└──╼ rosrun robert_beverage generate_qr_code 
Traceback (most recent call last):
  File "/home/user/workspace/robert/base/src/robert/robert_beverage/scripts/generate_qr_code", line 3, in <module>
    import qrcode
ImportError: No module named qrcode
```
Please read this Tutorial on how dependencies work in ROS http://wiki.ros.org/ROS/Tutorials/rosdep

In your case you could find that ROS by default has this dependency name **python-qrencode** for some qrencode library https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L2556
If you specify it in the **package.xml** file of **robert_beverage** package and run these instructions https://github.com/ucuapps/robert/blob/kinetic-devel/CONTRIBUTING.md#code-update new package will be installed.
This is a little bit different library from one which you are using so you need to learn how to call it.
If you have time please read this book about ROS https://www.cse.sc.edu/~jokane/agitr/ :)

2018-04-01 21:44 UTC, AndriyPt commented
Also please use **argparse** for arguments parsing https://docs.python.org/2/library/argparse.html

2018-04-01 21:44 UTC, AndriyPt requested changes
Please fix my comments

2018-04-05 09:09 UTC, v-lavrushko commented
Done

2018-04-12 19:21 UTC, AndriyPt requested changes
please remove venv files. It is not needed here. You are using Docker container which is isolated environment itself :)

2018-04-12 19:28 UTC, AndriyPt requested changes

2018-04-12 19:28 UTC, AndriyPt commented on robert_beverage/scripts/generate_qr_code
>  import rospy
please remove this dependency and ros node initialization code. For this utility you do not need ROS node.

2018-04-12 19:28 UTC, AndriyPt commented on robert_beverage/scripts/generate_qr_code
> +parser.add_argument('data', metavar='D', type=str, nargs=5)
please add separate flag for each option x, y, host, port and filename not single flag DATA :)

2018-04-17 15:56 UTC, v-lavrushko commented
Please check my code

2018-04-22 20:12 UTC, LyubomyrD commented
It successfully parsec the following
_python generate_qr_code a b c d e_

I guess, it is worse updating the code to prevent such situation.

2018-04-24 16:55 UTC, AndriyPt commented
please run the following commands
```bash
roscd robert_beverage/scripts
rosrun roslint pep8 ./generate_qr_code
```
You will see the following PEP8 errors:
```bash
./generate_qr_code:12:76: E502 the backslash is redundant between brackets
./generate_qr_code:13:50: E127 continuation line over-indented for visual indent
```
Please fix them and check PEP8 rules before requesting review :)

2018-04-26 11:53 UTC, v-lavrushko commented
Please, check my code. I checked it for PEP8 this time)

2018-04-29 21:08 UTC, LyubomyrD commented
@v-lavrushko The default values of the parameters are not defined. See here
https://github.com/ucuapps/robert/issues/30

2018-04-30 06:32 UTC, AndriyPt commented
https://docs.python.org/3/library/argparse.html#prog

2018-04-30 06:51 UTC, AndriyPt approved these changes

2018-04-30 06:51 UTC, merged